apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstream-workergroup.fullname" . }}
  labels:
    {{- include "logstream-workergroup.labels" . | nindent 4 }}
  annotations:
    # service.beta.kubernetes.io/aws-load-balancer-type: nlb
    # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: "5"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: "io.cribl.corp.infrastructure-logs"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: "ELB"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 10001
      targetPort: 10001
      protocol: TCP
      name: tcpjson
    - port: 9997
      targetPort: 9997
      protocol: TCP
      name: s2s
    - port: 10080
      targetPort: 10080
      protocol: TCP
      name: http
    - port: 10081
      targetPort: 10081
      protocol: TCP
      name: https
    - port: 5140
      targetPort: 5140
      protocol: TCP
      name: syslog
    - port: 8125
      targetPort: 8125
      protocol: TCP
      name: metrics
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: elastic
  selector:
    {{- include "logstream-workergroup.selectorLabels" . | nindent 4 }}
