---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-claim
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.config.pvType }}
  storageClassName:   {{ .Values.config.pvType }}
  {{- end}}
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: state-claim
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.config.pvType }}
  storageClassName:   {{ .Values.config.pvType }}
  {{- end}}
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.config.pvType }}
  storageClassName:   {{ .Values.config.pvType }}
  {{- end}}
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: groups-claim
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.config.pvType }}
  storageClassName:   {{ .Values.config.pvType }}
  {{- end}}
  resources:
    requests:
      storage: 4Gi