apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logstream-master.fullname" . }}
  labels:
    {{- include "logstream-master.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "logstream-master.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "logstream-master.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.criblImage.repository }}:{{ .Values.criblImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.criblImage.pullPolicy }}
          volumeMounts:
          - name: local-storage
            mountPath: {{ .Values.config.criblHome }}/local
          - name: data-storage
            mountPath: {{ .Values.config.criblHome }}/data
          - name: state-storage
            mountPath: {{ .Values.config.criblHome }}/state
          - name: groups-storage
            mountPath: {{ .Values.config.criblHome }}/groups
          {{- if  .Values.config.license }}
          - name: initial-config
            mountPath: /var/tmp/config_bits
          {{- end }}
          ports: 
            {{-  range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.config.healthPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.config.healthPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            # Allow Self-Signed Certs
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "{{ .Values.config.rejectSelfSignedCerts }}"
            - name: CRIBL_HOME
              value: "{{ .Values.config.criblHome }}"
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
            {{- if .Values.config.distributedKey }}
            - name: CRIBL_BEFORE_START_CMD_1
              value: "cp /var/tmp/config_bits/instance.yml {{ .Values.config.criblHome }}/local/_system/instance.yml"
            {{- end }}
            {{- if .Values.config.license }}
            - name: CRIBL_BEFORE_START_CMD_2
              value: "cp /var/tmp/config_bits/licenses.yml {{ .Values.config.criblHome }}/local/cribl/licenses.yml"
            {{- end }}
            {{- if .Values.config.groups }}
            - name: CRIBL_BEFORE_START_CMD_3
              value: "if [ ! -e {{ .Values.config.criblHome }}/local/cribl/mappings.yml ]; then cp /var/tmp/config_bits/groups.yml {{ .Values.config.criblHome }}/local/cribl/groups.yml; cp /var/tmp/config_bits/mappings.yml {{ .Values.config.criblHome }}/local/cribl/mappings.yml; fi"
            {{- end }}
            {{- if .Values.config.adminPassword }}
            - name: CRIBL_AFTER_START_CMD_1
              value: "sleep 60 && cp /var/tmp/config_bits/users.json {{ .Values.config.criblHome }}/local/cribl/auth/users.json"
            {{- end }}


      volumes:
        {{- if  .Values.config.license }}
        - name: initial-config
          secret: 
            secretName: logstream-master-config-{{ include "logstream-master.fullname" . }}
        {{- end }}
        - name: local-storage
          persistentVolumeClaim:
            claimName: local-claim
        - name: data-storage
          persistentVolumeClaim:
            claimName: data-claim
        - name: state-storage
          persistentVolumeClaim:
            claimName: state-claim
        - name: groups-storage
          persistentVolumeClaim:
            claimName: groups-claim
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

