apiVersion: v1
kind: Secret
type: Opaque
metadata: 
 name: logstream-license
stringData: 
{{- if  .Values.config.license }}
  licenses.yml: |
    licenses:
      - {{ .Values.config.license }}
{{- end }}
{{- if .Values.config.distributedKey }}
  instance.yml: |
    distributed:
      mode: master
      master:
        host: 0.0.0.0
        port: 4200
        tls:
          disabled: true
        ipWhitelistRegex: /.*/
        authToken: {{ .Values.config.distributedKey }}
        enabledWorkerRemoteAccess: false
{{- end }}
{{- if .Values.config.adminPassword }}
  users.json: |
    {"username":"admin","first":"admin","last":"admin","email":"admin","password":"{{ .Values.config.adminPassword }}"}
{{- end }}