---
# kubernetes_plugin: Give access to pods endpoint
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "pod-killer.fullname" . }}-{{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pod"]
    verbs: ["get", "list", "delete", "create","update", "patch", "watch"]
