# Default values for logstream-workergroup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cribl/cribl
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: "logstream-workergroup"
fullname: "logstream-workergroup"
fullnameOverride: ""

config: 
  host: logstream-master
  tag: kubernetes
  token: criblmaster

podAnnotations: {}


service:
  type: LoadBalancer
  annotations: {}

  svcPorts:
  - name: tcpjson
    containerPort: 10001
    protocol: TCP
  - name: s2s
    containerPort: 9997
    protocol: TCP
  - name: http
    containerPort: 10080
    protocol: TCP
  - name: https
    containerPort: 10081
    protocol: TCP    
  - name: syslog
    containerPort: 5140
    protocol: TCP
  - name: metrics
    containerPort: 8125
    protocol: TCP
  - name: elastic
    containerPort: 9200
    protocol: TCP

resources: 
  limits:
    cpu: 2000m
    memory: 1024Mi
  requests:
    cpu: 1250m
    memory: 256Mi


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 40
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80

