# Default values for logstream-workergroup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

rbac:
  create: true
  apiGroups: 
  - core
  resources:
  - pods
  verbs:
  - get
  - list
  annotations: {}

serviceAccount:
  create: true
  # name:

criblImage:
  repository: cribl/cribl
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 4.1.2

imagePullSecrets: []
nameOverride: ""

config: 
  host: logstream-leader-internal
  group: kubernetes
  token: ABCDEF01-1234-5678-ABCD-ABCDEF012345
  rejectSelfSignedCerts: 0
  probes: true
  livenessProbe:
    httpGet:
      path: /api/v1/health
      port: 9000
      scheme: HTTP
    initialDelaySeconds: 20
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /api/v1/health
      port: 9000
      scheme: HTTP
    initialDelaySeconds: 20
    failureThreshold: 3
  tlsLeader:
    enable: false
  tags: []

deployment: deployment

podAnnotations: {}

service:
  type: LoadBalancer
  ports:
  - name: tcpjson
    port: 10001
    protocol: TCP
  - name: s2s
    port: 9997
    protocol: TCP
  - name: http
    port: 10080
    protocol: TCP
  - name: https
    port: 10081
    protocol: TCP
  - name: syslog
    port: 5140
    protocol: TCP
  - name: metrics
    port: 8125
    protocol: TCP
  - name: elastic
    port: 9200
    protocol: TCP
  - name: hec
    port: 8088
    protocol: TCP
  - name: criblhttp
    port: 10200
    protocol: TCP
  - name: cribltcp
    port: 10300
    protocol: TCP

resources: 
  limits:
    cpu: 2000m
    memory: 4096Mi
  requests:
    cpu: 1250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

ingress:
  enable: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-stage
  ingress:
    - name: syslog-cribl-worker-ingress
      tls:
        - secretName: syslog-cribl-worker-ingress-tls
          hosts:
            - syslog.defnotavirus.com
      rules:
        - host: esyslog.defnotavirus.com
          paths:
            - path: /*
              port: 5140
