# Default values for logstream-workergroup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cribl/cribl
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: "logstream-workergroup"
fullname: "logstream-workergroup"
fullnameOverride: ""

config: 
  host: logstream-master
  tag: kubernetes
  token: criblmaster

podAnnotations: {}


service:
  type: LoadBalancer
  port: 9000


resources: 
  limits:
    cpu: 2000m
    memory: 1024Mi
  requests:
    cpu: 1250m
    memory: 256Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 40
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80

