---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logstream-leader.fullname" . }}
  labels:
    {{- include "logstream-leader.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "logstream-leader.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "logstream-leader.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "leader.pod" . | nindent 8 }}
